title: My Personal Webpage
email: geyaolin@gmail.com
description: 
  This website is only used for personal training and practices. 
baseurl: /Page
url: https://yaolinge.github.io
github_username: yaolinge

collections:
  authors:
    output: true

exclude: [notes, practice]

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"



theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
